"""Gmail SMTP delivery helpers for DropInvoice invoice PDFs."""

from __future__ import annotations

import logging
import mimetypes
import os
import smtplib
from email.message import EmailMessage
from pathlib import Path
from typing import Any

from invoice.gst_calculator import to_float

logger = logging.getLogger("dropinvoice.delivery.email")

DEFAULT_SMTP_HOST = "smtp.gmail.com"
DEFAULT_SMTP_PORT = 587


class EmailDeliveryError(Exception):
    """Raised when email invoice delivery cannot be completed."""


def send_invoice_email(
    recipient_email: str,
    pdf_path: str | Path,
    invoice_data: dict[str, Any],
) -> str:
    """Send an invoice PDF through Gmail SMTP and return the recipient address."""

    attachment_path = Path(pdf_path)
    if not attachment_path.exists():
        raise FileNotFoundError(f"Invoice PDF does not exist: {attachment_path}")

    message = build_invoice_email(recipient_email, attachment_path, invoice_data)
    smtp_host = os.getenv("GMAIL_SMTP_HOST", DEFAULT_SMTP_HOST)
    smtp_port = int(os.getenv("GMAIL_SMTP_PORT", str(DEFAULT_SMTP_PORT)))
    username = get_required_env("GMAIL_USERNAME")
    password = get_required_env("GMAIL_APP_PASSWORD")

    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as smtp:
            smtp.starttls()
            smtp.login(username, password)
            smtp.send_message(message)
    except Exception as exc:
        raise EmailDeliveryError(f"Could not send invoice email to {recipient_email}") from exc

    logger.info("Sent invoice %s email to %s", invoice_data.get("invoice_number"), recipient_email)
    return recipient_email


def build_invoice_email(
    recipient_email: str,
    pdf_path: Path,
    invoice_data: dict[str, Any],
) -> EmailMessage:
    """Build a multipart invoice email with a PDF attachment."""

    sender_email = get_required_env("GMAIL_USERNAME")
    invoice_number = str(invoice_data.get("invoice_number") or "DropInvoice")
    message = EmailMessage()
    message["From"] = sender_email
    message["To"] = recipient_email
    message["Subject"] = f"Invoice {invoice_number} from DropInvoice"
    message.set_content(build_plain_text_body(invoice_data))
    message.add_alternative(build_html_body(invoice_data), subtype="html")
    attach_pdf(message, pdf_path)
    return message


def build_plain_text_body(invoice_data: dict[str, Any]) -> str:
    """Build a plain-text fallback email body."""

    invoice_number = invoice_data.get("invoice_number") or "your invoice"
    grand_total = format_money(invoice_data.get("grand_total"))
    return (
        f"Hello,\n\n"
        f"Please find attached invoice {invoice_number}.\n"
        f"Grand Total: {grand_total}\n\n"
        f"Generated by DropInvoice."
    )


def build_html_body(invoice_data: dict[str, Any]) -> str:
    """Build a clean HTML email body for invoice delivery."""

    invoice_number = escape_html(invoice_data.get("invoice_number") or "your invoice")
    grand_total = escape_html(format_money(invoice_data.get("grand_total")))
    seller_name = escape_html(invoice_data.get("seller_name") or "DropInvoice user")

    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #111827; line-height: 1.5;">
        <p>Hello,</p>
        <p>Your invoice <strong>{invoice_number}</strong> from <strong>{seller_name}</strong> is attached.</p>
        <p style="font-size: 16px;"><strong>Grand Total:</strong> {grand_total}</p>
        <p style="color: #6b7280; font-size: 12px;">Generated by DropInvoice.</p>
      </body>
    </html>
    """.strip()


def attach_pdf(message: EmailMessage, pdf_path: Path) -> None:
    """Attach a PDF file to an email message."""

    mime_type, _ = mimetypes.guess_type(str(pdf_path))
    maintype, subtype = (mime_type or "application/pdf").split("/", maxsplit=1)

    with pdf_path.open("rb") as file_handle:
        message.add_attachment(
            file_handle.read(),
            maintype=maintype,
            subtype=subtype,
            filename=pdf_path.name,
        )


def get_required_env(name: str) -> str:
    """Return a required environment variable or raise an email delivery error."""

    value = os.getenv(name)
    if not value:
        raise EmailDeliveryError(f"{name} is required for email delivery.")

    return value


def format_money(value: Any) -> str:
    """Format a numeric value as an INR amount for email text."""

    numeric_value = to_float(value) or 0.0
    return f"INR {numeric_value:,.2f}"


def escape_html(value: Any) -> str:
    """Escape minimal HTML entities in email content."""

    text = str(value or "")
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
